/*
 * PORT_Config.h
 *
 *  Created on: Dec 15, 2023
 *      Author: hp
 */

#ifndef PORT_CONFIG_H_
#define PORT_CONFIG_H_

/* PORT A Direction */
#define DDRA_PIN0 0
#define DDRA_PIN1 0
#define DDRA_PIN2 0
#define DDRA_PIN3 0
#define DDRA_PIN4 0
#define DDRA_PIN5 0
#define DDRA_PIN6 0
#define DDRA_PIN7 0
/* PORT B Direction */
#define DDRB_PIN0 0
#define DDRB_PIN1 0
#define DDRB_PIN2 0
#define DDRB_PIN3 0
#define DDRB_PIN4 0
#define DDRB_PIN5 0
#define DDRB_PIN6 0
#define DDRB_PIN7 0
/* PORT C Direction */
#define DDRC_PIN0 0
#define DDRC_PIN1 0
#define DDRC_PIN2 0
#define DDRC_PIN3 0
#define DDRC_PIN4 0
#define DDRC_PIN5 0
#define DDRC_PIN6 0
#define DDRC_PIN7 0
/* PORT D Direction */
#define DDRD_PIN0 0
#define DDRD_PIN1 0
#define DDRD_PIN2 0
#define DDRD_PIN3 0
#define DDRD_PIN4 0
#define DDRD_PIN5 0
#define DDRD_PIN6 0
#define DDRD_PIN7 0

/* PORT A Value */
#define PORTA_PIN0 0
#define PORTA_PIN1 0
#define PORTA_PIN2 0
#define PORTA_PIN3 0
#define PORTA_PIN4 0
#define PORTA_PIN5 0
#define PORTA_PIN6 0
#define PORTA_PIN7 0
/* PORT B Value */
#define PORTB_PIN0 0
#define PORTB_PIN1 0
#define PORTB_PIN2 0
#define PORTB_PIN3 0
#define PORTB_PIN4 0
#define PORTB_PIN5 0
#define PORTB_PIN6 0
#define PORTB_PIN7 0
/* PORT C Value */
#define PORTC_PIN0 0
#define PORTC_PIN1 0
#define PORTC_PIN2 0
#define PORTC_PIN3 0
#define PORTC_PIN4 0
#define PORTC_PIN5 0
#define PORTC_PIN6 0
#define PORTC_PIN7 0
/* PORT D Value */
#define PORTD_PIN0 0
#define PORTD_PIN1 0
#define PORTD_PIN2 0
#define PORTD_PIN3 0
#define PORTD_PIN4 0
#define PORTD_PIN5 0
#define PORTD_PIN6 0
#define PORTD_PIN7 0

#define DDRA_CONC(DDRA_PIN0,DDRA_PIN1,DDRA_PIN2,DDRA_PIN3,DDRA_PIN4,DDRA_PIN5,DDRA_PIN6,DDRA_PIN7)  DDRA_CONC_HELPER(DDRA_PIN0,DDRA_PIN1,DDRA_PIN2,DDRA_PIN3,DDRA_PIN4,DDRA_PIN5,DDRA_PIN6,DDRA_PIN7)
#define DDRA_CONC_HELPER(DDRA_PIN0,DDRA_PIN1,DDRA_PIN2,DDRA_PIN3,DDRA_PIN4,DDRA_PIN5,DDRA_PIN6,DDRA_PIN7) DDRA_PIN0##DDRA_PIN1##DDRA_PIN2##DDRA_PIN3##DDRA_PIN4##DDRA_PIN5##DDRA_PIN6##DDRA_PIN7

#define DDRB_CONC(DDRB_PIN0,DDRB_PIN1,DDRB_PIN2,DDRB_PIN3,DDRB_PIN4,DDRB_PIN5,DDRB_PIN6,DDRB_PIN7)  DDRB_CONC_HELPER(DDRB_PIN0,DDRB_PIN1,DDRB_PIN2,DDRB_PIN3,DDRB_PIN4,DDRB_PIN5,DDRB_PIN6,DDRB_PIN7)
#define DDRB_CONC_HELPER(DDRB_PIN0,DDRB_PIN1,DDRB_PIN2,DDRB_PIN3,DDRB_PIN4,DDRB_PIN5,DDRB_PIN6,DDRB_PIN7) DDRB_PIN0##DDRB_PIN1##DDRB_PIN2##DDRB_PIN3##DDRB_PIN4##DDRB_PIN5##DDRB_PIN6##DDRB_PIN7

#define DDRC_CONC(DDRC_PIN0,DDRC_PIN1,DDRC_PIN2,DDRC_PIN3,DDRC_PIN4,DDRC_PIN5,DDRC_PIN6,DDRC_PIN7)  DDRC_CONC_HELPER(DDRC_PIN0,DDRC_PIN1,DDRC_PIN2,DDRC_PIN3,DDRC_PIN4,DDRC_PIN5,DDRC_PIN6,DDRC_PIN7)
#define DDRC_CONC_HELPER(DDRC_PIN0,DDRC_PIN1,DDRC_PIN2,DDRC_PIN3,DDRC_PIN4,DDRC_PIN5,DDRC_PIN6,DDRC_PIN7) DDRC_PIN0##DDRC_PIN1##DDRC_PIN2##DDRC_PIN3##DDRC_PIN4##DDRC_PIN5##DDRC_PIN6##DDRC_PIN7


#define DDRD_CONC(DDRD_PIN0,DDRD_PIN1,DDRD_PIN2,DDRD_PIN3,DDRD_PIN4,DDRD_PIN5,DDRD_PIN6,DDRD_PIN7)  DDRD_CONC_HELPER(DDRD_PIN0,DDRD_PIN1,DDRD_PIN2,DDRD_PIN3,DDRD_PIN4,DDRD_PIN5,DDRD_PIN6,DDRD_PIN7)
#define DDRD_CONC_HELPER(DDRD_PIN0,DDRD_PIN1,DDRD_PIN2,DDRD_PIN3,DDRD_PIN4,DDRD_PIN5,DDRD_PIN6,DDRD_PIN7) DDRD_PIN0##DDRD_PIN1##DDRD_PIN2##DDRD_PIN3##DDRD_PIN4##DDRD_PIN5##DDRD_PIN6##DDRD_PIN7






#endif /* PORT_CONFIG_H_ */
