/*
 * PORT_Program.c
 *
 *  Created on: Dec 15, 2023
 *      Author: sherif
 */
#include "STD.h"
#include "DIO_Register.h"
#include "PORT_Config.h"
#include "PORT_Interface.h"

void Port_void_voidInit(void)
{
	DDRA = CONC(DDRA_PIN7,DDRA_PIN6,DDRA_PIN5,DDRA_PIN4,DDRA_PIN3,DDRA_PIN2,DDRA_PIN1,DDRA_PIN0);
	DDRB = CONC(DDRB_PIN7,DDRB_PIN6,DDRB_PIN5,DDRB_PIN4,DDRB_PIN3,DDRB_PIN2,DDRB_PIN1,DDRB_PIN0);
	DDRC = CONC(DDRC_PIN7,DDRC_PIN6,DDRC_PIN5,DDRC_PIN4,DDRC_PIN3,DDRC_PIN2,DDRC_PIN1,DDRC_PIN0);
	DDRD = CONC(DDRD_PIN7,DDRD_PIN6,DDRD_PIN5,DDRD_PIN4,DDRD_PIN3,DDRD_PIN2,DDRD_PIN1,DDRD_PIN0);

	PORTA = CONC(PORTA_PIN7,PORTA_PIN6,PORTA_PIN5,PORTA_PIN4,PORTA_PIN3,PORTA_PIN2,PORTA_PIN1,PORTA_PIN0);
	PORTB = CONC(PORTB_PIN7,PORTB_PIN6,PORTB_PIN5,PORTB_PIN4,PORTB_PIN3,PORTB_PIN2,PORTB_PIN1,PORTB_PIN0);
	PORTC = CONC(PORTC_PIN7,PORTC_PIN6,PORTC_PIN5,PORTC_PIN4,PORTC_PIN3,PORTC_PIN2,PORTC_PIN1,PORTC_PIN0);
	PORTD = CONC(PORTD_PIN7,PORTD_PIN6,PORTD_PIN5,PORTD_PIN4,PORTD_PIN3,PORTD_PIN2,PORTD_PIN1,PORTD_PIN0);

}
